### ISSUE TITLE
Server app ./server_start.sh is not even listening

### ISSUE THREAD

**Issue by Richard98PL** [BrotherPatrix/my-tutorials#1]
Ports are unlocked (confirmed with nc -l 2456), but with netstat -tulpn you can just make yourself sure that this server file is idk... just not listening ;x wasted 20$

**Comment by BrotherPatrix** [comment]
The right port is 2457, and the 2456 is used for other purposes.
When you check with `netstat -tulpn | grep 245` you can see that only 2457 is probably active at that moment.
I'm not 100% sure what are the other ports are used for, but they are mentioned in the pdf documentation they provide.
![image](https://user-images.githubusercontent.com/13098741/107543461-ef2d6a80-6bd1-11eb-83ed-5072b12834ab.png)

**Comment by BrotherPatrix** [comment]
I've also explained here how you should test your server: https://github.com/BrotherPatrix/my-tutorials/tree/master/valheim-server-ubuntu-20-04#step-8---connecting-to-your-server
