### ISSUE TITLE
server not working

### ISSUE THREAD

**Issue by Richard98PL** [BrotherPatrix/my-tutorials#2]
did exactly the same, checked the ports - are opened
OVH and AWS services, servers still doesnt work, doesnt appear on steam list.
please fix

**Comment by BrotherPatrix** [comment]
Please check you firewall, either `ufw status` or `iptables -L`.
If ports are added to your list, check which one are active, should be `2457`;
Test the port locally then from outside, and you can use the netcat commands or others to test tcp/udp connections.
As mentioned in the guide, your server might not always appear in the steam server list or in-game server list, so you have to add it manually EXACTLY how it's described in Step 8.
I don't know how AWS and OVH firewall systems work, last time I worked on AWS was a few years ago, so my guess is you need to follow this guide: https://aws.amazon.com/blogs/mt/amazon-ec2-instance-port-forwarding-with-aws-systems-manager/

If you are still encountering problems, I'd suggest asking people on the official discord server: https://discord.gg/UYNBQtrN
